/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as BureauRouteRouteImport } from './app/_bureau/route'
import { Route as IndexRouteImport } from './app/index'
import { Route as ParentsIndexRouteImport } from './app/parents/index'
import { Route as ParentsReglagesRouteImport } from './app/parents/reglages'
import { Route as ParentsLieuxRouteImport } from './app/parents/lieux'
import { Route as ParentsImageModelRouteImport } from './app/parents/image-model'
import { Route as ParentsHeroesRouteImport } from './app/parents/heroes'
import { Route as ParentsElementsRouteImport } from './app/parents/elements'
import { Route as ParentsDoudousRouteImport } from './app/parents/doudous'
import { Route as ParentsCalculRouteImport } from './app/parents/calcul'
import { Route as DataSplatRouteImport } from './app/data.$'
import { Route as BureauBibliothequeRouteImport } from './app/_bureau/bibliotheque'
import { Route as BureauCalculIndexRouteImport } from './app/_bureau/calcul/index'
import { Route as BureauAventureIndexRouteImport } from './app/_bureau/aventure/index'
import { Route as BureauAventureIdRouteImport } from './app/_bureau/aventure/$id'

const BureauRouteRoute = BureauRouteRouteImport.update({
  id: '/_bureau',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsReglagesRoute = ParentsReglagesRouteImport.update({
  id: '/parents/reglages',
  path: '/parents/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsLieuxRoute = ParentsLieuxRouteImport.update({
  id: '/parents/lieux',
  path: '/parents/lieux',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsImageModelRoute = ParentsImageModelRouteImport.update({
  id: '/parents/image-model',
  path: '/parents/image-model',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsHeroesRoute = ParentsHeroesRouteImport.update({
  id: '/parents/heroes',
  path: '/parents/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsElementsRoute = ParentsElementsRouteImport.update({
  id: '/parents/elements',
  path: '/parents/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsDoudousRoute = ParentsDoudousRouteImport.update({
  id: '/parents/doudous',
  path: '/parents/doudous',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsCalculRoute = ParentsCalculRouteImport.update({
  id: '/parents/calcul',
  path: '/parents/calcul',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSplatRoute = DataSplatRouteImport.update({
  id: '/data/$',
  path: '/data/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BureauBibliothequeRoute = BureauBibliothequeRouteImport.update({
  id: '/bibliotheque',
  path: '/bibliotheque',
  getParentRoute: () => BureauRouteRoute,
} as any)
const BureauCalculIndexRoute = BureauCalculIndexRouteImport.update({
  id: '/calcul/',
  path: '/calcul/',
  getParentRoute: () => BureauRouteRoute,
} as any)
const BureauAventureIndexRoute = BureauAventureIndexRouteImport.update({
  id: '/aventure/',
  path: '/aventure/',
  getParentRoute: () => BureauRouteRoute,
} as any)
const BureauAventureIdRoute = BureauAventureIdRouteImport.update({
  id: '/aventure/$id',
  path: '/aventure/$id',
  getParentRoute: () => BureauRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bibliotheque': typeof BureauBibliothequeRoute
  '/data/$': typeof DataSplatRoute
  '/parents/calcul': typeof ParentsCalculRoute
  '/parents/doudous': typeof ParentsDoudousRoute
  '/parents/elements': typeof ParentsElementsRoute
  '/parents/heroes': typeof ParentsHeroesRoute
  '/parents/image-model': typeof ParentsImageModelRoute
  '/parents/lieux': typeof ParentsLieuxRoute
  '/parents/reglages': typeof ParentsReglagesRoute
  '/parents/': typeof ParentsIndexRoute
  '/aventure/$id': typeof BureauAventureIdRoute
  '/aventure/': typeof BureauAventureIndexRoute
  '/calcul/': typeof BureauCalculIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bibliotheque': typeof BureauBibliothequeRoute
  '/data/$': typeof DataSplatRoute
  '/parents/calcul': typeof ParentsCalculRoute
  '/parents/doudous': typeof ParentsDoudousRoute
  '/parents/elements': typeof ParentsElementsRoute
  '/parents/heroes': typeof ParentsHeroesRoute
  '/parents/image-model': typeof ParentsImageModelRoute
  '/parents/lieux': typeof ParentsLieuxRoute
  '/parents/reglages': typeof ParentsReglagesRoute
  '/parents': typeof ParentsIndexRoute
  '/aventure/$id': typeof BureauAventureIdRoute
  '/aventure': typeof BureauAventureIndexRoute
  '/calcul': typeof BureauCalculIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_bureau': typeof BureauRouteRouteWithChildren
  '/_bureau/bibliotheque': typeof BureauBibliothequeRoute
  '/data/$': typeof DataSplatRoute
  '/parents/calcul': typeof ParentsCalculRoute
  '/parents/doudous': typeof ParentsDoudousRoute
  '/parents/elements': typeof ParentsElementsRoute
  '/parents/heroes': typeof ParentsHeroesRoute
  '/parents/image-model': typeof ParentsImageModelRoute
  '/parents/lieux': typeof ParentsLieuxRoute
  '/parents/reglages': typeof ParentsReglagesRoute
  '/parents/': typeof ParentsIndexRoute
  '/_bureau/aventure/$id': typeof BureauAventureIdRoute
  '/_bureau/aventure/': typeof BureauAventureIndexRoute
  '/_bureau/calcul/': typeof BureauCalculIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bibliotheque'
    | '/data/$'
    | '/parents/calcul'
    | '/parents/doudous'
    | '/parents/elements'
    | '/parents/heroes'
    | '/parents/image-model'
    | '/parents/lieux'
    | '/parents/reglages'
    | '/parents/'
    | '/aventure/$id'
    | '/aventure/'
    | '/calcul/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bibliotheque'
    | '/data/$'
    | '/parents/calcul'
    | '/parents/doudous'
    | '/parents/elements'
    | '/parents/heroes'
    | '/parents/image-model'
    | '/parents/lieux'
    | '/parents/reglages'
    | '/parents'
    | '/aventure/$id'
    | '/aventure'
    | '/calcul'
  id:
    | '__root__'
    | '/'
    | '/_bureau'
    | '/_bureau/bibliotheque'
    | '/data/$'
    | '/parents/calcul'
    | '/parents/doudous'
    | '/parents/elements'
    | '/parents/heroes'
    | '/parents/image-model'
    | '/parents/lieux'
    | '/parents/reglages'
    | '/parents/'
    | '/_bureau/aventure/$id'
    | '/_bureau/aventure/'
    | '/_bureau/calcul/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BureauRouteRoute: typeof BureauRouteRouteWithChildren
  DataSplatRoute: typeof DataSplatRoute
  ParentsCalculRoute: typeof ParentsCalculRoute
  ParentsDoudousRoute: typeof ParentsDoudousRoute
  ParentsElementsRoute: typeof ParentsElementsRoute
  ParentsHeroesRoute: typeof ParentsHeroesRoute
  ParentsImageModelRoute: typeof ParentsImageModelRoute
  ParentsLieuxRoute: typeof ParentsLieuxRoute
  ParentsReglagesRoute: typeof ParentsReglagesRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_bureau': {
      id: '/_bureau'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BureauRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/reglages': {
      id: '/parents/reglages'
      path: '/parents/reglages'
      fullPath: '/parents/reglages'
      preLoaderRoute: typeof ParentsReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/lieux': {
      id: '/parents/lieux'
      path: '/parents/lieux'
      fullPath: '/parents/lieux'
      preLoaderRoute: typeof ParentsLieuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/image-model': {
      id: '/parents/image-model'
      path: '/parents/image-model'
      fullPath: '/parents/image-model'
      preLoaderRoute: typeof ParentsImageModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/heroes': {
      id: '/parents/heroes'
      path: '/parents/heroes'
      fullPath: '/parents/heroes'
      preLoaderRoute: typeof ParentsHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/elements': {
      id: '/parents/elements'
      path: '/parents/elements'
      fullPath: '/parents/elements'
      preLoaderRoute: typeof ParentsElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/doudous': {
      id: '/parents/doudous'
      path: '/parents/doudous'
      fullPath: '/parents/doudous'
      preLoaderRoute: typeof ParentsDoudousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/calcul': {
      id: '/parents/calcul'
      path: '/parents/calcul'
      fullPath: '/parents/calcul'
      preLoaderRoute: typeof ParentsCalculRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/$': {
      id: '/data/$'
      path: '/data/$'
      fullPath: '/data/$'
      preLoaderRoute: typeof DataSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_bureau/bibliotheque': {
      id: '/_bureau/bibliotheque'
      path: '/bibliotheque'
      fullPath: '/bibliotheque'
      preLoaderRoute: typeof BureauBibliothequeRouteImport
      parentRoute: typeof BureauRouteRoute
    }
    '/_bureau/calcul/': {
      id: '/_bureau/calcul/'
      path: '/calcul'
      fullPath: '/calcul/'
      preLoaderRoute: typeof BureauCalculIndexRouteImport
      parentRoute: typeof BureauRouteRoute
    }
    '/_bureau/aventure/': {
      id: '/_bureau/aventure/'
      path: '/aventure'
      fullPath: '/aventure/'
      preLoaderRoute: typeof BureauAventureIndexRouteImport
      parentRoute: typeof BureauRouteRoute
    }
    '/_bureau/aventure/$id': {
      id: '/_bureau/aventure/$id'
      path: '/aventure/$id'
      fullPath: '/aventure/$id'
      preLoaderRoute: typeof BureauAventureIdRouteImport
      parentRoute: typeof BureauRouteRoute
    }
  }
}

interface BureauRouteRouteChildren {
  BureauBibliothequeRoute: typeof BureauBibliothequeRoute
  BureauAventureIdRoute: typeof BureauAventureIdRoute
  BureauAventureIndexRoute: typeof BureauAventureIndexRoute
  BureauCalculIndexRoute: typeof BureauCalculIndexRoute
}

const BureauRouteRouteChildren: BureauRouteRouteChildren = {
  BureauBibliothequeRoute: BureauBibliothequeRoute,
  BureauAventureIdRoute: BureauAventureIdRoute,
  BureauAventureIndexRoute: BureauAventureIndexRoute,
  BureauCalculIndexRoute: BureauCalculIndexRoute,
}

const BureauRouteRouteWithChildren = BureauRouteRoute._addFileChildren(
  BureauRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BureauRouteRoute: BureauRouteRouteWithChildren,
  DataSplatRoute: DataSplatRoute,
  ParentsCalculRoute: ParentsCalculRoute,
  ParentsDoudousRoute: ParentsDoudousRoute,
  ParentsElementsRoute: ParentsElementsRoute,
  ParentsHeroesRoute: ParentsHeroesRoute,
  ParentsImageModelRoute: ParentsImageModelRoute,
  ParentsLieuxRoute: ParentsLieuxRoute,
  ParentsReglagesRoute: ParentsReglagesRoute,
  ParentsIndexRoute: ParentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
